theme: jekyll-theme-slate
title: NetDash
description: The NetDash project's goal is to create an interface to allow delegation of specific network management tasks to IT teams outside of a central network team. 
